[package]
name = "hello_remote_world"
version = "0.1.0"
authors = ["VS Code <vscode@microsoft.com>"]

[[bin]]
name = "hello_remote_world"
path = "test-project/src/main.rs"

[[test]]
name = "tests"
path = "test-project/tests/conn_test.rs"

[dev-dependencies]
postgres = "0.19"
